# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Create .env
        run: |
          echo "DATABASE_URL=${{secrets.DATABASE_URL}}" >> .env
          echo "IMAGEKIT_PUBLIC_KEY=${{secrets.IMAGEKIT_PUBLIC_KEY}}" >> .env
          echo "IMAGEKIT_PRIVATE_KEY=${{secrets.IMAGEKIT_PRIVATE_KEY}}" >> .env
          echo "IMAGEKIT_URL_ENDPOINT=${{secrets.IMAGEKIT_URL_ENDPOINT}}" >> .env
          echo "UPCARE_SECRET_KEY=${{secrets.UPCARE_SECRET_KEY}}" >> .env
          echo "UPCARE_PUBLIC_KEY=${{secrets.UPCARE_PUBLIC_KEY}}" >> .env
          echo "MAILTRAP_TOKEN=${{secrets.MAILTRAP_TOKEN}}" >> .env
          echo "SENDER_EMAIL=${{secrets.SENDER_EMAIL}}" >> .env
          echo "CROSS_ORIGIN=${{secrets.CROSS_ORIGIN}}" >> .env
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm run build --if-present
