# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          IMAGEKIT_PUBLIC_KEY: ${{ secrets.IMAGEKIT_PUBLIC_KEY }}
          IMAGEKIT_PRIVATE_KEY: ${{ secrets.IMAGEKIT_PRIVATE_KEY }}
          IMAGEKIT_URL_ENDPOINT: ${{ secrets.IMAGEKIT_URL_ENDPOINT }}
          UPCARE_SECRET_KEY: ${{ secrets.UPCARE_SECRET_KEY }}
          UPCARE_PUBLIC_KEY: ${{ secrets.UPCARE_PUBLIC_KEY }}
          MAILTRAP_TOKEN: ${{ secrets.MAILTRAP_TOKEN }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      - run: npm run build --if-present
